name: Deploy to Staging

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://thiru-susuki.github.io/github-integration/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Simulate Deployment
        run: echo "Deploying to staging..."

      - name: Mark Deployment Success
        run: echo "Deployment completed"
